version: '3.7'
services:
  bingo:
    container_name: bingo
    image: "cr.yandex/${registry_id}/bingo"
    restart: always
    network_mode: "host"
    tty: true
  nginx:
    container_name: nginx
    image: "cr.yandex/${registry_id}/nginx"
    restart: always
    network_mode: "host"
